"""
Django settings for p2Django project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from os.path import join
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'uawh##i5hc3=hdn+pw)uq3bb6queoxxo=_d@pzp9*6m+lhi@-!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'materializecssform',
    'apps.imagen',
    'apps.perfil',
    'social_django',
    'pwa'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

#Authentication_Backends
AUTHENTICATION_BACKENDS= [
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend'
] 

ROOT_URLCONF = 'p2Django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [join(BASE_DIR, 'plantilla')
],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'p2Django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  #Modificar por gestor de base que Ud utiliza
        'NAME': 'p2django', #Mantener asi
        'USER': 'root', #Cambio de usuario si desea asociar la DB a otro
        #'PASSWORD': 'jeremayo123', #Contraseña del usuario
        'PASSWORD': 'duoc', #Contraseña del usuario

        'HOST': 'localhost', #Medio de conexion
        'PORT': '3306'  #Puerto de conexion
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = join(BASE_DIR, 'plantilla', 'static_root')
STATICFILES_DIRS = [
    join(BASE_DIR, 'plantilla')
]
# Rutas para media/ archivos que se suben por la pagina...
MEDIA_URL = '/media/'
MEDIA_ROOT = join(BASE_DIR, 'media')

## Rutas para logear
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/perfil'
LOGOUT_URL = 'salir'
LOGOUT_REDIRECT_URL = 'ingreso'

##Valores para iniciar sesión con Facebook
SOCIAL_AUTH_FACEBOOK_KEY = '421529248875480'
SOCIAL_AUTH_FACEBOOK_SECRET= 'e26a80c4d7928be12baf1ce94334c4dd'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email', 'user_link']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'name, email, picture.type(Large), link'
}
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_DATA = [
    ('name','name'),
    ('email','email'),
    ('picture','picture'),
    ('link','user_link')
]

##Envío de 
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'djangochileautos@gmail.com  '
EMAIL_HOST_PASSWORD = 'chileautos123'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


#Archivos de configuracion , variables de configuracion para el service worket
PWA_SERVICE_WORKER_PATH = join(BASE_DIR,'media','sw','serviceworker.js')
